# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The PrintSafe Project
email: wgrover@engr.ucr.edu
description: > # this means to ignore newlines until "baseurl:"
  219 Materials Science and Engineering Building
  University of California, Riverside<br>
  Riverside, CA 92521
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://printsafe.org" # the base hostname & protocol for your site
twitter_username: print_safe

# Build settings
markdown: kramdown




collections:
  people:
    output: true
  research:
    output: true
  education:
    output: true
  hnbfpr:
    output: true


    

